---
core:
    num_workers: 100


inventory:
    plugin: nornir.plugins.inventory.simple.SimpleInventory
    options:
        host_file: "/Users/mmrti1/desktop/netmiko/hosts.yaml"
        group_file: "/Users/mmrti1/desktop/netmiko/groups.yaml"
        defaults_file: "/Users/mmrti1/desktop/netmiko/defaults.yaml"
