---
  R2:
    hostname: 192.168.2.2
    platform: 'ios'
    username: cisco
    password: cisco
    groups:
        - cisco_group

R3:
    hostname: 192.168.4.2
    platform: 'ios'
    username: cisco
    password: cisco
    groups:
        - cisco_group

R4:
    hostname: 192.168.5.2
    platform: 'ios'
    username: cisco
    password: cisco
    groups:
        - cisco_group
